### ISSUE TITLE
Any upcoming schedule of this repository?

### ISSUE THREAD

**Issue by wongwaijeremy** [chaklim/jyutping-table-parser#1]
Hi CL, I am Jeremy :)
I have extreme interest on Chinese Phonetics. I know there are online resource (the service is down unfortunately) that collects the historical pronunciation as well. I can provide that resource I backed up.

**Comment by chaklim** [comment]
Hi :)
and sorry no upcoming schedule for this repository.

If the resources is related to history pronunciation, maybe it should be in another repository :)
