### ISSUE TITLE
Incorrectly Grouped References

### ISSUE THREAD

**Issue by nathanhammond** [chaklim/jyutping-table-parser#3]
Hello @chaklim! I spent the last day building a project whose output is identical to this in order to check for output correctness by having two separate implementations. My approach works by extracting values directly from the source PDF to make it independent from some application's PDF text extraction algorithm.

You can see the project here:
https://github.com/nathanhammond/parse-jyutping-table-full

The underlying code is still a complete mess, but it works. In checking for output correctness I discovered an issue where your parser is assigning some characters as a reference instead of as a top-level character:
`["5002", "5225", "5294", "5A7E", "5DD3", "5ECF", "5F54", "609E", "60B3", "6231", "672E", "69E9", "6DE8", "7522", "75F2", "7D55", "7DA0", "7DD6", "7E15", "860A", "8AAA", "8F40", "9115", "919E", "9292", "92B3", "9304", "93AD", "95B1", "984F", "985A", "98EE", "9920", "9A08", "9C2E"]`

除左呢個問題之外 all other output is identical, implying that the two independent implementations are correctly extracting the contents from the source PDF.

My next comparison is with LSHK's list, again to check for correctness: https://github.com/lshk-org/jyutping-table

**Comment by chaklim** [comment]
Hi @nathanhammond!
Thank you for your findings :)

Tests are added to cover those cases and should be fixed.
Confirm that 29,145 characters have been extracted.

**Comment by nathanhammond** [comment]
Output is now identical, save for newline at EOF. Given the two wholly-different approaches I'm very confident in the accuracy.

```diff
532639c532639
< ]
\ No newline at end of file
---
> ]
```

Footnote, my Cantonese-related code eventually all gets moved to the https://github.com/cantonese organization. Threw you an invite. 😊
